
export default function Head() {
    return (
        <>
            <title>Gifbox</title>
            <meta content="width=device-width, initial-scale=1" name="viewport" />
            <meta
                name="description"
                content="Generated by create next app and Made with ❤️ by Mehmet Pekcan"
            />
            <link rel="icon" href="/gifbox.png" />
        </>
    );
}